wh=1
s=Sikkerhedsmargin=3
r=Reperationer=0.5
def prmenu():
    print("1)MM 850nm")
    print("2)MM 1300nm")
    print("3)SM 1310nm")
    print("4)SM 1550nm")
    print("5)stop program")
prmenu()
Menunr=int(input("vælg menu nr."))


while wh == 1:
    if Menunr==1:
        x=float(input("indtast afsendersignal"))
        y=float(input("indtast modtagersignal"))
        print("Bruttuoverskud="+str(x-y))
        br=float(x-y)
        a=int(input("indtast antal splidsninger"))
        b=int(input("indtast antal konnekteringer"))
        km=float(input("indtast antal km fiber"))
        sp=float(a*0.1)
        print("splidsninger i db=",sp)
        k=float(b*0.5)
        print("konnektering i db=",k)
        lm=float(2.2*km+k+sp)
        print("linkmargin=",2.2*km+k+sp)
        print("sikkerhedmargin=",s)
        print("reperation=",r)
        print("Netto overskud=",br-lm-s-r)
        print("du har valgt menu nr. 1")
        prmenu()
        Menunr=int(input("vælg menu nr."))

    if Menunr==2:
        x=float(input("indtast afsendersignal"))
        y=float(input("indtast modtagersignal"))
        print("Bruttuoverskud="+str(x-y))
        br=float(x-y)
        a=int(input("indtast antal splidsninger"))
        b=int(input("indtast antal konnekteringer"))
        km=float(input("indtast antal km fiber"))
        sp=float(a*0.1)
        print("splidsninger i db=",sp)
        k=float(b*0.5)
        print("konnektering i db=",k)
        lm=float(0.6*km+k+sp)
        print("linkmargin=",0.6*km+k+sp)
        print("sikkerhedmargin=",s)
        print("reperation=",r)
        print("Netto overskud=",br-lm-s-r)
        print("du har valgt menu nr. 2")
        prmenu()
        Menunr=int(input("vælg menu nr."))

    if Menunr==3:
        x=float(input("indtast afsendersignal"))
        y=float(input("indtast modtagersignal"))
        print("Bruttuoverskud="+str(x-y))
        br=float(x-y)
        a=int(input("indtast antal splidsninger"))
        b=int(input("indtast antal konnekteringer"))
        km=float(input("indtast antal km fiber"))
        sp=float(a*0.1)
        print("splidsninger i db=",sp)
        k=float(b*0.5)
        print("konnektering i db=",k)
        lm=float(0.35*km+k+sp)
        print("linkmargin=",0.35*km+k+sp)
        print("sikkerhedmargin=",s)
        print("reperation=",r)
        print("Netto overskud=",br-lm-s-r)
        print("du har valgt menu nr. 3")
        prmenu()
        Menunr=int(input("vælg menu nr."))

    if Menunr==4:
        x=float(input("indtast afsendersignal"))
        y=float(input("indtast modtagersignal"))
        print("Bruttuoverskud="+str(x-y))
        br=float(x-y)
        a=int(input("indtast antal splidsninger"))
        b=int(input("indtast antal konnekteringer"))
        km=float(input("indtast antal km fiber"))
        sp=float(a*0.1)
        print("splidsninger i db=",sp)
        k=float(b*0.5)
        print("konnektering i db=",k)
        lm=float(0.2*km+k+sp)
        print("linkmargin=",0.2*km+k+sp)
        print("sikkerhedmargin=",s)
        print("reperation=",r)
        print("Netto overskud=",br-lm-s-r)
        print("du har valgt menu nr. 3")
        prmenu()
        Menunr=int(input("vælg menu nr."))

        if Menunr==5:
            print("programmet stopper")
            wh = 2
